CREATE TABLE members (NAME TEXT, CHAT INTEGER, ID INTEGER NOT NULL PRIMARY KEY);
CREATE TABLE matches (MATCH_NAME TEXT, MEMBER_ID INTEGER, ID INTEGER NOT NULL PRIMARY KEY);
ALTER TABLE members ADD PREVIOUS_NAME TEXT;
